baseURL: https://xicu.net/
title: Xicu Mar√≠
theme: 
  - hugo-adobe-pdf-embed
  - hugo-shortcode-gallery
  - PaperMod

enableEmoji: true
enableRobotsTXT: true

params:
  description: I'm Xicu, an Electronic Engineer passionate about Electrons, Computers and Philosophy. Here you will find my blog, projects and more.
  env: production
  defaultTheme: auto
  keywords: [Blog, Portfolio, Electronic Engineer, Robotics, Embedded Systems, Software Development, FPGA]
  
  profileMode:
    enabled: true
    imageUrl: home/profile.jpg
    imageWidth: 140
    imageHeight: 140

  cover:
    linkFullImages: true

  label:
    iconLight: icons/logo-light.png
    iconDark: icons/logo-dark.png
    iconHeight: 44

  ShowReadingTime: true
  
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  # Share buttons
  ShowShareButtons: true
  ShareButtons: ["x", "linkedin", "whatsapp", "reddit", "telegram", "facebook"]

  # Adobe PDF Viewer
  adobeClientId: "5e4106dab71f4a17bcabc294a0a8a637"

  # Favicons
  assets:
    favicon: icons/favicon.ico
    favicon16x16: icons/favicon-16x16.png
    favicon32x32: icons/favicon-32x32.png
    apple_touch_icon: icons/apple-touch-icon.png

# Language configuration
defaultContentLanguage: en
defaultContentLanguageInSubdir: true

# Goldmark configuration
# markup:
#   goldmark:
#     renderer:
#       unsafe: true
#   renderHooks:
#       image:
#         enableDefault: true

markup:

  # Goldmark configuration
  goldmark:
    extensions:
      taskList: true
      table: true
      extras:
        delete:
          enable: false
        insert:
          enable: false
        mark:
          enable: false
        subscript:
          enable: false
        superscript:
          enable: false
      strikethrough: false

  # Code highlighting
  highlight:
    codeFences: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false

  # Table of contents
  tableOfContents:
    ordered: true